name: Publish
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - run: cargo install cargo-edit
      - name: Update version in Cargo.toml
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          sed -i 's/^version = ".*"/version = "'$VERSION'"/' Cargo.toml
      - name: Publish to crates.io
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CRATES_IO_TOKEN }}

