name: Publish
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-check-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo install cargo-edit
      - run: |
          VERSION=${GITHUB_REF_NAME#?}
          cargo set-version $VERSION
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CRATES_IO_TOKEN }}
          args: --allow-dirty
